import type { Category, Merchant } from "./types";

export const CATEGORIES: { id: Category; label: string }[] = [
  { id: "streaming", label: "Streaming" },
  { id: "music", label: "Music & audio" },
  { id: "fitness", label: "Fitness" },
  { id: "software", label: "Software" },
  { id: "ai", label: "AI" },
  { id: "news", label: "News" },
  { id: "shopping", label: "Shopping" },
  { id: "food", label: "Food" },
  { id: "cloud", label: "Cloud" },
  { id: "gaming", label: "Gaming" },
  { id: "other", label: "Other" },
];

export const merchants: Merchant[] = [
  {
    id: "netflix",
    name: "Netflix",
    category: "streaming",
    aliases: ["NETFLIX.COM", "NETFLIX", "NFLX"],
    color: "#B91C1C",
    letter: "N",
    typicalPrice: 17.99,
    cycle: "monthly",
    cancelUrl: "https://www.netflix.com/cancelplan",
    manageUrl: "https://www.netflix.com/account",
    cancelDifficulty: "easy",
    darkPatterns: [
      "They ask why you are leaving, then offer a pause instead of an end.",
      "Profiles and continue-watching are framed as things you will lose forever.",
    ],
    cancelSteps: [
      {
        title: "Open the cancel page",
        body: "Use Vale’s door. Sign in if Netflix asks.",
      },
      {
        title: "Decline the pause",
        body: "Pause keeps the billing relationship. Choose cancel membership.",
        warning: "Do not tap “Remind me later.”",
      },
      {
        title: "Keep the confirmation",
        body: "You should see an end date. Screenshot it. You keep access until then.",
      },
    ],
  },
  {
    id: "disney-plus",
    name: "Disney+",
    category: "streaming",
    aliases: ["DISNEYPLUS", "DISNEY PLUS", "DISNEY+", "WALT DISNEY"],
    color: "#1E3A8A",
    letter: "D",
    typicalPrice: 13.99,
    cycle: "monthly",
    cancelUrl: "https://www.disneyplus.com/account",
    manageUrl: "https://www.disneyplus.com/account",
    cancelDifficulty: "easy",
    darkPatterns: [
      "A discount often appears the moment you click cancel.",
      "Bundle language (“you’ll lose Hulu too”) is used to freeze the decision.",
    ],
    cancelSteps: [
      {
        title: "Open Account",
        body: "Sign in, then open Subscription or Billing.",
      },
      {
        title: "Cancel the subscription",
        body: "Choose cancel — not pause, not a cheaper tier — unless you truly want to keep paying.",
        warning: "A 3-month discount is still a subscription. It will rise again.",
      },
      {
        title: "Confirm the end date",
        body: "Screenshot the confirmation. Disney+ usually lasts until the period you already paid for.",
      },
    ],
  },
  {
    id: "hulu",
    name: "Hulu",
    category: "streaming",
    aliases: ["HULU", "HULU COM"],
    color: "#166534",
    letter: "H",
    typicalPrice: 17.99,
    cycle: "monthly",
    cancelUrl: "https://secure.hulu.com/account",
    manageUrl: "https://secure.hulu.com/account",
    cancelDifficulty: "easy",
    darkPatterns: [
      "Cancel is nested under Account, not on the home screen.",
      "They offer to pause or switch plans before they let you leave.",
    ],
    cancelSteps: [
      { title: "Open your Hulu account", body: "Use Vale’s door and sign in." },
      {
        title: "Find Cancel",
        body: "Look under Subscription or Your membership — not under Pause.",
      },
      {
        title: "Finish without a new plan",
        body: "Confirm cancellation. Ignore “are you sure” screens unless you changed your mind.",
      },
    ],
  },
  {
    id: "max",
    name: "Max",
    category: "streaming",
    aliases: ["MAX.COM", "HBO MAX", "HBOMAX", "WMG *MAX"],
    color: "#4338CA",
    letter: "M",
    typicalPrice: 16.99,
    cycle: "monthly",
    cancelUrl: "https://play.max.com/settings/subscription",
    manageUrl: "https://play.max.com/settings",
    cancelDifficulty: "easy",
    darkPatterns: [
      "If you subscribed through a cable bundle or Amazon, Max’s own site cannot cancel it.",
      "They push an annual plan while you are trying to leave.",
    ],
    cancelSteps: [
      {
        title: "Check who bills you",
        body: "If the bank line says Amazon, Apple, or a cable company, cancel there — not on Max.",
        warning: "The wrong door is the most common reason people think they “can’t cancel.”",
      },
      {
        title: "Otherwise open Max settings",
        body: "Subscription → Cancel. Decline the annual save.",
      },
      { title: "Save the end date", body: "Screenshot the confirmation page." },
    ],
  },
  {
    id: "paramount-plus",
    name: "Paramount+",
    category: "streaming",
    aliases: ["PARAMOUNTPLUS", "PARAMOUNT+", "CBS ALL ACCESS"],
    color: "#1E40AF",
    letter: "P",
    typicalPrice: 12.99,
    cycle: "monthly",
    cancelUrl: "https://www.paramountplus.com/account/",
    manageUrl: "https://www.paramountplus.com/account/",
    cancelDifficulty: "medium",
    darkPatterns: [
      "Account pages vary by whether you signed up on the site, an app, or a partner.",
      "They emphasize what you will lose more than what you will stop paying.",
    ],
    cancelSteps: [
      {
        title: "Open Account",
        body: "If you cannot see Cancel, you probably subscribed through Amazon, Apple, or a wireless carrier.",
      },
      { title: "Cancel on the original store", body: "Use that store’s subscription list. Vale’s Apple and Google doors cover most of these." },
      { title: "Confirm", body: "Keep a screenshot of the cancellation date." },
    ],
  },
  {
    id: "peacock",
    name: "Peacock",
    category: "streaming",
    aliases: ["PEACOCK", "PEACOCKTV", "NBCUNIVERSAL"],
    color: "#F59E0B",
    letter: "P",
    typicalPrice: 13.99,
    cycle: "monthly",
    cancelUrl: "https://www.peacocktv.com/account",
    manageUrl: "https://www.peacocktv.com/account",
    cancelDifficulty: "easy",
    darkPatterns: ["A cheaper ad-supported plan is offered as if it were the only alternative to staying."],
    cancelSteps: [
      { title: "Open your account", body: "Sign in through Vale’s door." },
      { title: "Cancel membership", body: "Choose cancel, not a downgrade, unless you want the cheaper plan." },
      { title: "Confirm", body: "Screenshot the end date." },
    ],
  },
  {
    id: "youtube-premium",
    name: "YouTube Premium",
    category: "streaming",
    aliases: ["GOOGLE *YouTube", "YOUTUBE PREMIUM", "GOOGLE YOUTUBE", "YTPREMIUM"],
    color: "#B91C1C",
    letter: "Y",
    typicalPrice: 13.99,
    cycle: "monthly",
    cancelUrl: "https://www.youtube.com/paid_memberships",
    manageUrl: "https://www.youtube.com/paid_memberships",
    cancelDifficulty: "easy",
    darkPatterns: ["Family plan language makes one person’s cancel feel like it will hurt everyone."],
    cancelSteps: [
      { title: "Open Paid memberships", body: "This is the real list — not the YouTube home screen." },
      { title: "Manage Premium", body: "Cancel membership. Ads will return after the paid period ends." },
      { title: "Confirm", body: "Google emails a receipt. Keep it." },
    ],
  },
  {
    id: "spotify",
    name: "Spotify",
    category: "music",
    aliases: ["SPOTIFY", "SPOTIFY USA", "SPOTIFY AB"],
    color: "#15803D",
    letter: "S",
    typicalPrice: 11.99,
    cycle: "monthly",
    cancelUrl: "https://www.spotify.com/account/subscription/",
    manageUrl: "https://www.spotify.com/account/subscription/",
    cancelDifficulty: "easy",
    darkPatterns: [
      "They offer a discounted plan on the cancel screen.",
      "Playlists are implied to vanish. They do not. You just hear ads again.",
    ],
    cancelSteps: [
      { title: "Open Subscription", body: "Use Vale’s door on the web, not the mobile app — the app hides this." },
      {
        title: "Cancel Premium",
        body: "Click change or cancel plan. Skip the cheaper offer unless you want it.",
        warning: "The mobile app is a dark pattern. Cancel on the website.",
      },
      { title: "Confirm", body: "You keep Premium until the date shown." },
    ],
  },
  {
    id: "apple-music",
    name: "Apple Music",
    category: "music",
    aliases: ["APPLE MUSIC", "APPLE.COM/BILL MUSIC"],
    color: "#FB7185",
    letter: "A",
    typicalPrice: 10.99,
    cycle: "monthly",
    cancelUrl: "https://apps.apple.com/account/subscriptions",
    manageUrl: "https://apps.apple.com/account/subscriptions",
    cancelDifficulty: "medium",
    darkPatterns: [
      "The bank line often says Apple.com/bill, not Apple Music.",
      "Subscriptions live in Apple ID, not inside the Music app’s obvious screens.",
    ],
    cancelSteps: [
      { title: "Open Apple Subscriptions", body: "This list is the truth. Music, iCloud, apps, and TV+ all sit here." },
      { title: "Select Apple Music", body: "Cancel subscription. Confirm." },
      { title: "Wait for the period to end", body: "Apple bills through the current term. You keep access until then." },
    ],
  },
  {
    id: "audible",
    name: "Audible",
    category: "music",
    aliases: ["AUDIBLE", "AUDIBLE*"],
    color: "#F59E0B",
    letter: "A",
    typicalPrice: 14.95,
    cycle: "monthly",
    cancelUrl: "https://www.audible.com/account/overview",
    manageUrl: "https://www.audible.com/account/overview",
    cancelDifficulty: "medium",
    darkPatterns: [
      "Unused credits are used as a reason to stay.",
      "They offer a cheaper plan rather than a clean exit.",
    ],
    cancelSteps: [
      { title: "Open Account overview", body: "Look for Membership details, not “pause.”" },
      {
        title: "Cancel membership",
        body: "If you have credits, use them before the end date or they may expire — that is by design.",
        warning: "Do not let unused credits talk you into another year.",
      },
      { title: "Confirm", body: "Keep the email. Purchased titles usually remain in your library." },
    ],
  },
  {
    id: "amazon-prime",
    name: "Amazon Prime",
    category: "shopping",
    aliases: ["AMAZON PRIME", "PRIME VIDEO", "AMZNPRIME"],
    color: "#B45309",
    letter: "P",
    typicalPrice: 14.99,
    cycle: "monthly",
    cancelUrl: "https://www.amazon.com/gp/primecentral",
    manageUrl: "https://www.amazon.com/gp/primecentral",
    cancelDifficulty: "medium",
    darkPatterns: [
      "Cancel is labeled “Update, pause, or cancel” — pause is first.",
      "Shipping and video are bundled so one decision feels like three losses.",
    ],
    cancelSteps: [
      { title: "Open Prime Central", body: "This is the management portal your statement never names." },
      {
        title: "End membership",
        body: "Choose cancel, not pause. You can still shop. You just pay for shipping again.",
        warning: "“Pause for 3 months” is how they keep the anniversary bill.",
      },
      { title: "Confirm the last day", body: "Amazon usually keeps benefits until the period you already paid." },
    ],
  },
  {
    id: "apple-subscriptions",
    name: "Apple subscriptions",
    category: "other",
    aliases: ["APPLE.COM/BILL", "APPLE COM BILL", "APPLE.COM/BILL ITUNES"],
    color: "#44403C",
    letter: "A",
    typicalPrice: 9.99,
    cycle: "monthly",
    cancelUrl: "https://apps.apple.com/account/subscriptions",
    manageUrl: "https://apps.apple.com/account/subscriptions",
    cancelDifficulty: "medium",
    darkPatterns: [
      "The statement says Apple. It does not say which app.",
      "This is how gyms, newspapers, and streaming services hide inside a single charge.",
    ],
    notice:
      "This is a bill aggregator. Open the list, then cancel the apps you do not use — not “Apple” itself.",
    cancelSteps: [
      {
        title: "Open the Apple subscription list",
        body: "Every app that bills through Apple ID lives here. This is the missing portal.",
      },
      {
        title: "Identify the quiet ones",
        body: "Sort by name. Cancel anything you do not recognize or have not opened.",
        warning: "Cancelling iCloud can affect photos. Read the name before you tap.",
      },
      { title: "Confirm each one", body: "Apple shows an expiry date per subscription. Screenshot the list." },
    ],
  },
  {
    id: "google-play",
    name: "Google Play subscriptions",
    category: "other",
    aliases: ["GOOGLE *Play", "GOOGLE PLAY", "GOOGLE *TEMPORARY HOLD"],
    color: "#3B82F6",
    letter: "G",
    typicalPrice: 9.99,
    cycle: "monthly",
    cancelUrl: "https://play.google.com/store/account/subscriptions",
    manageUrl: "https://play.google.com/store/account/subscriptions",
    cancelDifficulty: "medium",
    darkPatterns: ["One bank line can hide several Android apps."],
    notice: "This is a bill aggregator. The Play subscriptions page is the real list.",
    cancelSteps: [
      { title: "Open Play subscriptions", body: "Sign in with the Google account that is billed." },
      { title: "Cancel the unused apps", body: "Tap each quiet title → Cancel subscription." },
      { title: "Confirm", body: "Google sends an email per cancellation." },
    ],
  },
  {
    id: "google-one",
    name: "Google One",
    category: "cloud",
    aliases: ["GOOGLE ONE", "GOOGLE*ONE", "GOOGLE  ONE", "GOOGLE STORAGE"],
    color: "#4285F4",
    letter: "1",
    typicalPrice: 2.99,
    cycle: "monthly",
    cancelUrl: "https://one.google.com/settings",
    manageUrl: "https://one.google.com/settings",
    cancelDifficulty: "easy",
    darkPatterns: [
      "Storage warnings appear as you cancel. Photos do not vanish the moment you click.",
      "Gemini / AI Premium is sometimes bundled. Read the plan name before you cancel.",
    ],
    notice: "Manage storage and the plan at one.google.com — not the Gmail settings gear.",
    cancelSteps: [
      { title: "Open Google One settings", body: "Sign in with the same Gmail that is billed." },
      {
        title: "Cancel membership",
        body: "Change plan or cancel. You keep the paid storage until the period ends, then drop to 15 GB.",
      },
      { title: "Confirm", body: "Google emails a receipt. If Gemini came with this plan, check that too." },
    ],
  },
  {
    id: "gemini",
    name: "Gemini",
    category: "ai",
    aliases: [
      "GEMINI ADVANCED",
      "GOOGLE GEMINI",
      "GOOGLE AI PRO",
      "GOOGLE AI PLUS",
      "GOOGLE ONE AI",
      "GEMINI",
      "GOOGLE *GEMINI",
    ],
    color: "#8E75B2",
    letter: "G",
    typicalPrice: 19.99,
    cycle: "monthly",
    cancelUrl: "https://one.google.com/ai",
    manageUrl: "https://myaccount.google.com/payments-and-subscriptions",
    cancelDifficulty: "easy",
    darkPatterns: [
      "The bank line may say Google One, not Gemini.",
      "AI Premium and Google One storage can look like two products and bill as one.",
    ],
    notice:
      "Google often bills this as Google One AI Premium or Google AI Pro. Cancel on one.google.com or Google payments — not inside the Gemini chat.",
    cancelSteps: [
      { title: "Open Google AI / One", body: "Use Vale’s door. The chat app hides billing." },
      {
        title: "Cancel the AI plan",
        body: "If storage came with it, decide whether to keep a cheaper Google One plan.",
      },
      { title: "Confirm", body: "You keep access until the date already paid." },
    ],
  },
  {
    id: "planet-fitness",
    name: "Planet Fitness",
    category: "fitness",
    aliases: ["PLANET FITNESS", "PLANET FIT", "PLNT FITNESS", "PF GYM"],
    color: "#9333EA",
    letter: "P",
    typicalPrice: 24.99,
    cycle: "monthly",
    cancelUrl: "https://www.planetfitness.com/gyms",
    manageUrl: "https://www.planetfitness.com/gyms",
    cancelDifficulty: "hostile",
    phone: "Varies by home club",
    notice:
      "Most clubs require you to cancel in person or by mail, with notice before the next draft. The website will not do this for you.",
    darkPatterns: [
      "There is often no cancel button online. That is the product.",
      "Staff may offer a freeze or a cheaper club instead of a cancellation form.",
      "Missing the notice window means they draft you again.",
    ],
    cancelSteps: [
      {
        title: "Find your home club",
        body: "Use the locator. Call and ask: “Do you accept cancellation in person, by email, or by mail — and how many days of notice?”",
      },
      {
        title: "Get it in writing",
        body: "Fill their form. Take a photo of the signed copy, or send certified mail and keep the receipt.",
        warning: "A verbal “you’re cancelled” is how people stay billed for a year.",
      },
      {
        title: "Watch the next two drafts",
        body: "If they bill after the notice period, dispute the charge with your bank using the form photo.",
      },
    ],
  },
  {
    id: "la-fitness",
    name: "LA Fitness",
    category: "fitness",
    aliases: ["LA FITNESS", "LAFITNESS", "L A FITNESS"],
    color: "#1D4ED8",
    letter: "L",
    typicalPrice: 34.99,
    cycle: "monthly",
    cancelUrl: "https://www.lafitness.com/Pages/clublocator.aspx",
    manageUrl: "https://www.lafitness.com/Pages/clublocator.aspx",
    cancelDifficulty: "hostile",
    notice: "Typically requires written notice to your home club. Online cancel is rarely available.",
    darkPatterns: [
      "Contracts hide the notice period in small print.",
      "They prefer freeze over cancel because freeze keeps the file open.",
    ],
    cancelSteps: [
      { title: "Ask the club for the required method", body: "In person, email, or mail. Get the address in writing." },
      {
        title: "Send written notice",
        body: "Include your name, member ID, and a clear “I am cancelling my membership.” Keep a copy.",
      },
      { title: "Calendar the last legal draft", body: "If they bill after that, you have a paper trail." },
    ],
  },
  {
    id: "equinox",
    name: "Equinox",
    category: "fitness",
    aliases: ["EQUINOX", "EQUINOX FITNESS"],
    color: "#111827",
    letter: "E",
    typicalPrice: 260,
    cycle: "monthly",
    cancelUrl: "https://www.equinox.com/clubs",
    manageUrl: "https://www.equinox.com/clubs",
    cancelDifficulty: "hostile",
    notice: "Often requires an in-club visit and 30 days of notice. High-pressure retention is common.",
    darkPatterns: [
      "A manager will be called. Their job is to keep the membership.",
      "Prepaid periods and initiation fees are used to make leaving feel wasteful.",
    ],
    cancelSteps: [
      { title: "Read your agreement", body: "Find the notice window and the required method before you walk in." },
      {
        title: "Visit with a script",
        body: "“I am here to cancel. I do not want a freeze, a pause, or a downgrade. Please process the cancellation and give me written confirmation.”",
        warning: "Do not sit for the retention meeting if you already decided.",
      },
      { title: "Leave with paper", body: "No confirmation, no cancellation. Photo the form before you go." },
    ],
  },
  {
    id: "classpass",
    name: "ClassPass",
    category: "fitness",
    aliases: ["CLASSPASS", "CLASS PASS"],
    color: "#E11D48",
    letter: "C",
    typicalPrice: 49,
    cycle: "monthly",
    cancelUrl: "https://classpass.com/settings",
    manageUrl: "https://classpass.com/settings",
    cancelDifficulty: "medium",
    darkPatterns: ["Unused credits expire, which is used to justify staying one more month."],
    cancelSteps: [
      { title: "Open Settings", body: "Membership or Billing — cancel plan." },
      { title: "Skip the pause", body: "Pause still occupies a billing relationship." },
      { title: "Use leftover credits", body: "If they survive until the end date, spend them. Then confirm cancel." },
    ],
  },
  {
    id: "peloton",
    name: "Peloton",
    category: "fitness",
    aliases: ["PELOTON", "ONEPELOTON"],
    color: "#DC2626",
    letter: "P",
    typicalPrice: 44,
    cycle: "monthly",
    cancelUrl: "https://members.onepeloton.com/profile",
    manageUrl: "https://members.onepeloton.com/profile",
    cancelDifficulty: "medium",
    darkPatterns: ["Hardware and software are bundled in conversation so cancelling All-Access feels like bricking the bike."],
    cancelSteps: [
      { title: "Open your Peloton profile", body: "Membership → Cancel. The bike still works for free rides." },
      { title: "Confirm you are cancelling All-Access", body: "Not a pause. Not a gift month." },
      { title: "Keep the email", body: "Your end date should be in writing." },
    ],
  },
  {
    id: "calm",
    name: "Calm",
    category: "fitness",
    aliases: ["CALM.COM", "CALM APP", "CALM *"],
    color: "#0369A1",
    letter: "C",
    typicalPrice: 69.99,
    cycle: "yearly",
    cancelUrl: "https://www.calm.com/account",
    manageUrl: "https://www.calm.com/account",
    cancelDifficulty: "medium",
    darkPatterns: [
      "Yearly billing hides the cost until the anniversary.",
      "If you subscribed through Apple or Google, Calm’s site cannot cancel it.",
    ],
    cancelSteps: [
      {
        title: "Check the original store",
        body: "If your statement says Apple.com/bill or Google Play, use those doors instead.",
      },
      { title: "Otherwise open Calm account", body: "Subscription → Cancel renewal." },
      { title: "Confirm", body: "You usually keep access until the year you already paid for ends." },
    ],
  },
  {
    id: "headspace",
    name: "Headspace",
    category: "fitness",
    aliases: ["HEADSPACE"],
    color: "#F97316",
    letter: "H",
    typicalPrice: 12.99,
    cycle: "monthly",
    cancelUrl: "https://www.headspace.com/account",
    manageUrl: "https://www.headspace.com/account",
    cancelDifficulty: "medium",
    darkPatterns: ["App-store billing is the usual trap. The Headspace app will not always show Cancel."],
    cancelSteps: [
      { title: "Find who bills you", body: "Apple, Google, or Headspace directly." },
      { title: "Cancel on that store", body: "Turn off renewal. Keep access until the period ends." },
      { title: "Confirm", body: "Screenshot the subscriptions list." },
    ],
  },
  {
    id: "adobe",
    name: "Adobe",
    category: "software",
    aliases: ["ADOBE", "ADOBE *PHOTOSHOP", "ADOBE CREATIVE", "ADOBE *Adobe"],
    color: "#DC2626",
    letter: "A",
    typicalPrice: 54.99,
    cycle: "monthly",
    cancelUrl: "https://account.adobe.com/plans",
    manageUrl: "https://account.adobe.com/plans",
    cancelDifficulty: "hard",
    notice: "Annual plans cancelled early can carry a substantial fee. Read the plan type before you confirm.",
    darkPatterns: [
      "Early termination fees on annual plans are the retention strategy.",
      "They offer a cheaper photography plan on the way out.",
    ],
    cancelSteps: [
      { title: "Open Adobe plans", body: "See whether you are monthly or annual. The fee only applies to some annual contracts." },
      {
        title: "Cancel the plan",
        body: "If a fee appears and you are close to renewal, waiting may be cheaper. Vale is honest about this.",
        warning: "Do not click a new discounted annual plan to “save.” That restarts the trap.",
      },
      { title: "Download your files", body: "Cloud storage access can change after the term ends." },
    ],
  },
  {
    id: "microsoft-365",
    name: "Microsoft 365",
    category: "software",
    aliases: ["MICROSOFT*365", "MSFT *365", "MICROSOFT 365", "OFFICE 365"],
    color: "#2563EB",
    letter: "M",
    typicalPrice: 9.99,
    cycle: "monthly",
    cancelUrl: "https://account.microsoft.com/services",
    manageUrl: "https://account.microsoft.com/services",
    cancelDifficulty: "easy",
    darkPatterns: ["They emphasize that Word and Excel will become read-only."],
    cancelSteps: [
      { title: "Open Microsoft services", body: "This is the account portal, not office.com." },
      { title: "Turn off recurring billing", body: "You keep the apps until the date shown." },
      { title: "Confirm", body: "Save the confirmation email." },
    ],
  },
  {
    id: "dropbox",
    name: "Dropbox",
    category: "cloud",
    aliases: ["DROPBOX"],
    color: "#1D4ED8",
    letter: "D",
    typicalPrice: 11.99,
    cycle: "monthly",
    cancelUrl: "https://www.dropbox.com/account/plan",
    manageUrl: "https://www.dropbox.com/account/plan",
    cancelDifficulty: "easy",
    darkPatterns: ["Storage overage warnings appear as you cancel."],
    cancelSteps: [
      { title: "Download anything over 2 GB", body: "Free accounts shrink. Do this first." },
      { title: "Open Plan", body: "Cancel Plus or Professional." },
      { title: "Confirm", body: "You revert at the end of the paid period." },
    ],
  },
  {
    id: "icloud",
    name: "iCloud+",
    category: "cloud",
    aliases: ["APPLE.COM/BILL ICLOUD", "ICLOUD+"],
    color: "#6366F1",
    letter: "i",
    typicalPrice: 2.99,
    cycle: "monthly",
    cancelUrl: "https://apps.apple.com/account/subscriptions",
    manageUrl: "https://apps.apple.com/account/subscriptions",
    cancelDifficulty: "medium",
    darkPatterns: ["Downgrading can stop photo backups. Apple leads with that fear."],
    cancelSteps: [
      { title: "Check what you actually use", body: "If photos depend on iCloud, cancelling is a storage decision, not a streaming one." },
      { title: "Open Apple subscriptions", body: "Cancel iCloud+ or downgrade to free 5 GB." },
      { title: "Wait for the term to end", body: "Then make sure the library still fits." },
    ],
  },
  {
    id: "chatgpt",
    name: "ChatGPT Plus",
    category: "ai",
    aliases: ["OPENAI", "CHATGPT", "OPENAI *CHATGPT"],
    color: "#0F172A",
    letter: "G",
    typicalPrice: 20,
    cycle: "monthly",
    cancelUrl: "https://chatgpt.com/#settings",
    manageUrl: "https://chatgpt.com/#settings",
    cancelDifficulty: "easy",
    darkPatterns: ["Settings are behind the account menu, not a billing URL your bank would ever print."],
    cancelSteps: [
      { title: "Open ChatGPT settings", body: "Your plan or Billing. Manage subscription." },
      { title: "Cancel Plus", body: "You keep Plus until the period ends, then return to the free tier." },
      { title: "Confirm", body: "If you paid through Apple or Google, cancel on that store instead." },
    ],
  },
  {
    id: "claude",
    name: "Claude Pro",
    category: "ai",
    aliases: ["ANTHROPIC", "CLAUDE.AI", "CLAUDE PRO"],
    color: "#D97706",
    letter: "C",
    typicalPrice: 20,
    cycle: "monthly",
    cancelUrl: "https://claude.ai/settings/billing",
    manageUrl: "https://claude.ai/settings/billing",
    cancelDifficulty: "easy",
    darkPatterns: ["Billing is a quiet settings link, never named on the statement."],
    cancelSteps: [
      { title: "Open billing settings", body: "Use Vale’s door." },
      { title: "Cancel the plan", body: "Confirm. Access lasts until the date shown." },
      { title: "Keep the receipt", body: "Stripe or Anthropic will email it." },
    ],
  },
  {
    id: "notion",
    name: "Notion",
    category: "software",
    aliases: ["NOTION", "NOTION LABS"],
    color: "#111827",
    letter: "N",
    typicalPrice: 10,
    cycle: "monthly",
    cancelUrl: "https://www.notion.so/my-account",
    manageUrl: "https://www.notion.so/my-account",
    cancelDifficulty: "easy",
    darkPatterns: ["Workspace owners must cancel — members cannot. That confusion keeps teams paying."],
    cancelSteps: [
      { title: "Open Settings & members", body: "Plans → Downgrade or cancel. You must be an owner." },
      { title: "Export if you need to", body: "Do this before the plan ends if you rely on extras." },
      { title: "Confirm", body: "The workspace remains; paid features go away." },
    ],
  },
  {
    id: "canva",
    name: "Canva Pro",
    category: "software",
    aliases: ["CANVA", "CANVA PTY"],
    color: "#0EA5E9",
    letter: "C",
    typicalPrice: 14.99,
    cycle: "monthly",
    cancelUrl: "https://www.canva.com/settings/billing",
    manageUrl: "https://www.canva.com/settings/billing",
    cancelDifficulty: "easy",
    darkPatterns: ["Brand-kit fear is used to keep Pro."],
    cancelSteps: [
      { title: "Open Billing", body: "Cancel plan. Download any Pro-only assets you need." },
      { title: "Confirm", body: "You revert at period end." },
      { title: "Screenshot", body: "Keep the confirmation." },
    ],
  },
  {
    id: "github-copilot",
    name: "GitHub Copilot",
    category: "ai",
    aliases: ["GITHUB", "GITHUB COPILOT"],
    color: "#111827",
    letter: "G",
    typicalPrice: 10,
    cycle: "monthly",
    cancelUrl: "https://github.com/settings/billing",
    manageUrl: "https://github.com/settings/billing",
    cancelDifficulty: "easy",
    darkPatterns: ["Billing is under Settings, not in the editor where you feel the product."],
    cancelSteps: [
      { title: "Open GitHub billing", body: "Plans and usage → Copilot." },
      { title: "Cancel Copilot", body: "Confirm. Your code stays. The suggestions stop at period end." },
      { title: "Confirm", body: "GitHub emails a receipt." },
    ],
  },
  {
    id: "linkedin",
    name: "LinkedIn Premium",
    category: "other",
    aliases: ["LINKEDIN", "LINKEDIN PREM", "LINKEDIN PREMIUM"],
    color: "#1D4ED8",
    letter: "in",
    typicalPrice: 29.99,
    cycle: "monthly",
    cancelUrl: "https://www.linkedin.com/premium/manage",
    manageUrl: "https://www.linkedin.com/premium/manage",
    cancelDifficulty: "medium",
    darkPatterns: [
      "InMail credits and “who viewed your profile” are the fear screens.",
      "Annual prepay is pushed hard at cancel time.",
    ],
    cancelSteps: [
      { title: "Open Premium manage", body: "This URL is the door. The app buries it." },
      {
        title: "Cancel Premium",
        body: "Turn off auto-renew. You keep Premium until the date on the page.",
        warning: "Do not start a free trial of a different Premium tier. That is a new bill.",
      },
      { title: "Confirm", body: "Screenshot manage premium after it says renew is off." },
    ],
  },
  {
    id: "nyt",
    name: "The New York Times",
    category: "news",
    aliases: ["NYTIMES", "NEW YORK TIMES", "NY TIMES", "NYT"],
    color: "#111827",
    letter: "T",
    typicalPrice: 17,
    cycle: "monthly",
    cancelUrl: "https://myaccount.nytimes.com/",
    manageUrl: "https://myaccount.nytimes.com/",
    cancelDifficulty: "hard",
    phone: "1-800-591-9233",
    darkPatterns: [
      "Online cancel is sometimes hidden; chat or phone is offered instead.",
      "A discounted rate appears only after you insist you are leaving.",
    ],
    cancelSteps: [
      { title: "Open My Account", body: "Look for Subscriptions → Cancel. If it is missing, that is the dark pattern." },
      {
        title: "Use chat or the phone if the button is gone",
        body: "Say: “I want to cancel. I do not want a pause or a discount.” Repeat it once.",
        warning: "The discount is real money — take it only if you still read the Times.",
      },
      { title: "Get the confirmation number", body: "No number, no cancel. Ask them to email it." },
    ],
  },
  {
    id: "wsj",
    name: "The Wall Street Journal",
    category: "news",
    aliases: ["WSJ", "WALL STREET JOURNAL", "DOW JONES"],
    color: "#1F2937",
    letter: "W",
    typicalPrice: 38.99,
    cycle: "monthly",
    cancelUrl: "https://customercenter.wsj.com/",
    manageUrl: "https://customercenter.wsj.com/",
    cancelDifficulty: "hard",
    darkPatterns: ["Retention agents are trained to offer a lower rate. The cancel control is often not self-serve."],
    cancelSteps: [
      { title: "Open Customer Center", body: "Find subscription details." },
      { title: "Cancel in writing if needed", body: "Chat: “Cancel my subscription. Please email confirmation.”" },
      { title: "Keep the email", body: "News sites rebill on anniversary dates. The email is your proof." },
    ],
  },
  {
    id: "doordash",
    name: "DashPass",
    category: "food",
    aliases: ["DOORDASH", "DASHPASS", "DOOR DASH"],
    color: "#DC2626",
    letter: "D",
    typicalPrice: 9.99,
    cycle: "monthly",
    cancelUrl: "https://www.doordash.com/dashpass",
    manageUrl: "https://www.doordash.com/dashpass",
    cancelDifficulty: "easy",
    darkPatterns: ["They show how much you “saved” this year, which may include fees you would not have paid."],
    cancelSteps: [
      { title: "Open DashPass", body: "Manage → Cancel DashPass." },
      { title: "Skip the savings recap", body: "That screen exists to stop your finger." },
      { title: "Confirm", body: "You can still order. You just pay regular fees." },
    ],
  },
  {
    id: "uber-one",
    name: "Uber One",
    category: "food",
    aliases: ["UBER ONE", "UBER *ONE", "UBERONE"],
    color: "#111827",
    letter: "U",
    typicalPrice: 9.99,
    cycle: "monthly",
    cancelUrl: "https://account.uber.com/one",
    manageUrl: "https://account.uber.com/one",
    cancelDifficulty: "easy",
    darkPatterns: ["Rides and eats are bundled so cancelling feels like losing both."],
    cancelSteps: [
      { title: "Open Uber One", body: "Account → Uber One → Cancel membership." },
      { title: "Confirm", body: "Benefits last until the period ends." },
      { title: "Screenshot", body: "Keep it. App UIs change." },
    ],
  },
  {
    id: "instacart",
    name: "Instacart+",
    category: "food",
    aliases: ["INSTACART", "INSTACART+"],
    color: "#F59E0B",
    letter: "I",
    typicalPrice: 9.99,
    cycle: "monthly",
    cancelUrl: "https://www.instacart.com/store/account",
    manageUrl: "https://www.instacart.com/store/account",
    cancelDifficulty: "easy",
    darkPatterns: ["Free delivery math assumes you would have placed the same orders anyway."],
    cancelSteps: [
      { title: "Open Account", body: "Instacart+ → Cancel." },
      { title: "Confirm", body: "Decline the annual “save.”" },
      { title: "Keep access until the date shown", body: "Then fees return." },
    ],
  },
  {
    id: "hellofresh",
    name: "HelloFresh",
    category: "food",
    aliases: ["HELLOFRESH", "HELLO FRESH"],
    color: "#65A30D",
    letter: "H",
    typicalPrice: 79.99,
    cycle: "weekly",
    cancelUrl: "https://www.hellofresh.com/my-account/deliveries/menu",
    manageUrl: "https://www.hellofresh.com/my-account/deliveries/menu",
    cancelDifficulty: "medium",
    darkPatterns: [
      "Skip is easier to find than Cancel, which keeps the account in a billing loop.",
      "Deadlines for skipping are easy to miss, so a box ships anyway.",
    ],
    cancelSteps: [
      { title: "Skip any box already in motion if you can", body: "Then go to Account settings → Subscription." },
      {
        title: "Cancel, do not skip forever",
        body: "Skipping is how they still own next Tuesday.",
        warning: "If a box already shipped, you will be charged for it. That is normal — then you cancel.",
      },
      { title: "Confirm by email", body: "You should receive a cancellation confirmation." },
    ],
  },
  {
    id: "nordvpn",
    name: "NordVPN",
    category: "software",
    aliases: ["NORDVPN", "NORDSEC", "NORD VPN"],
    color: "#1E3A8A",
    letter: "N",
    typicalPrice: 12.99,
    cycle: "monthly",
    cancelUrl: "https://my.nordaccount.com/dashboard/nordvpn/",
    manageUrl: "https://my.nordaccount.com/dashboard/nordvpn/",
    cancelDifficulty: "medium",
    darkPatterns: ["Long prepaid terms. Auto-renew is the trap, not the monthly sticker price."],
    cancelSteps: [
      { title: "Open Nord Account", body: "Turn off auto-renew first if you are prepaid." },
      { title: "Cancel if monthly", body: "Follow billing → cancel subscription." },
      { title: "Confirm", body: "Keep the email. VPNs often rebill on the anniversary." },
    ],
  },
  {
    id: "grammarly",
    name: "Grammarly",
    category: "software",
    aliases: ["GRAMMARLY"],
    color: "#15803D",
    letter: "G",
    typicalPrice: 12,
    cycle: "monthly",
    cancelUrl: "https://account.grammarly.com/subscription",
    manageUrl: "https://account.grammarly.com/subscription",
    cancelDifficulty: "easy",
    darkPatterns: ["Annual plans discounted at cancel time restart the year."],
    cancelSteps: [
      { title: "Open subscription", body: "Cancel Premium." },
      { title: "Decline a new annual plan", body: "Unless you still write with it every day." },
      { title: "Confirm", body: "The free editor remains." },
    ],
  },
  {
    id: "duolingo",
    name: "Duolingo Super",
    category: "other",
    aliases: ["DUOLINGO"],
    color: "#65A30D",
    letter: "D",
    typicalPrice: 12.99,
    cycle: "monthly",
    cancelUrl: "https://www.duolingo.com/settings/super",
    manageUrl: "https://www.duolingo.com/settings/super",
    cancelDifficulty: "medium",
    darkPatterns: ["Streak fear. The streak survives on the free tier."],
    cancelSteps: [
      { title: "See who bills you", body: "Apple, Google, or Duolingo." },
      { title: "Cancel Super", body: "Your streak does not require Super." },
      { title: "Confirm", body: "Hearts and ads return. That is the product, not a punishment." },
    ],
  },
  {
    id: "discord-nitro",
    name: "Discord Nitro",
    category: "other",
    aliases: ["DISCORD", "DISCORD NITRO"],
    color: "#5865F2",
    letter: "D",
    typicalPrice: 9.99,
    cycle: "monthly",
    cancelUrl: "https://discord.com/channels/@me",
    manageUrl: "https://discord.com/channels/@me",
    cancelDifficulty: "easy",
    darkPatterns: ["Boosted servers are used as a reason to keep Nitro for everyone else."],
    cancelSteps: [
      { title: "Open User Settings", body: "Subscriptions → Nitro → Cancel." },
      { title: "Confirm", body: "Boosts may drop at period end. Tell your server if that matters." },
      { title: "Keep the receipt", body: "Discord emails it." },
    ],
  },
  {
    id: "xbox-game-pass",
    name: "Xbox Game Pass",
    category: "gaming",
    aliases: ["XBOX", "GAME PASS", "MICROSOFT*XBOX"],
    color: "#15803D",
    letter: "X",
    typicalPrice: 19.99,
    cycle: "monthly",
    cancelUrl: "https://account.microsoft.com/services",
    manageUrl: "https://account.microsoft.com/services",
    cancelDifficulty: "easy",
    darkPatterns: ["Games you installed will stop working — they say this as if the files were yours forever."],
    cancelSteps: [
      { title: "Open Microsoft services", body: "Game Pass → Cancel." },
      { title: "Confirm", body: "Finish anything you are mid-campaign before the end date." },
      { title: "Keep the email", body: "Billing is through Microsoft account, not the console home." },
    ],
  },
  {
    id: "playstation-plus",
    name: "PlayStation Plus",
    category: "gaming",
    aliases: ["PLAYSTATION", "SONY PLAYSTATION", "PS PLUS", "PLAYSTATIONNETWORK"],
    color: "#1D4ED8",
    letter: "P",
    typicalPrice: 17.99,
    cycle: "monthly",
    cancelUrl: "https://www.playstation.com/en-us/playstation-network/",
    manageUrl: "https://www.playstation.com/account/",
    cancelDifficulty: "medium",
    darkPatterns: ["Console UI buries subscriptions under Account settings, not the store you open every day."],
    cancelSteps: [
      { title: "Open PlayStation account on the web", body: "Subscriptions. It is clearer than the TV UI." },
      { title: "Cancel Plus", body: "Turn off auto-renew." },
      { title: "Confirm", body: "Online play may stop at period end. Save the date." },
    ],
  },
];

const byId = new Map(merchants.map((m) => [m.id, m]));

export function getMerchant(id: string | null | undefined) {
  if (!id) return null;
  return byId.get(id) ?? null;
}

export function searchMerchants(query: string) {
  const q = query.trim().toLowerCase();
  if (!q) return merchants.slice();
  return merchants.filter((m) => {
    if (m.name.toLowerCase().includes(q)) return true;
    if (m.category.includes(q as Category)) return true;
    return m.aliases.some((a) => a.toLowerCase().includes(q));
  });
}

export const difficultyCopy: Record<Merchant["cancelDifficulty"], string> = {
  easy: "The door is on the website.",
  medium: "The door exists. It is just not where the app wants you to look.",
  hard: "They will talk. You may need a phone or a chat.",
  hostile: "They designed this so you cannot finish it in a browser.",
};
