import { daysAgoIso, daysFromNowIso } from "./dates";
import type { SavingsEvent, Subscription } from "./types";

export function demoSubscriptions(): Subscription[] {
  return [
    {
      id: "demo-netflix",
      merchantId: "netflix",
      name: "Netflix",
      amount: 17.99,
      cycle: "monthly",
      lastUsedAt: daysAgoIso(2),
      startedAt: daysAgoIso(420),
      nextChargeAt: daysFromNowIso(11),
      status: "active",
      bankDescriptor: "NETFLIX.COM",
    },
    {
      id: "demo-disney",
      merchantId: "disney-plus",
      name: "Disney+",
      amount: 13.99,
      cycle: "monthly",
      lastUsedAt: daysAgoIso(94),
      startedAt: daysAgoIso(510),
      nextChargeAt: daysFromNowIso(4),
      status: "active",
      bankDescriptor: "DISNEYPLUS",
    },
    {
      id: "demo-hulu",
      merchantId: "hulu",
      name: "Hulu",
      amount: 17.99,
      cycle: "monthly",
      lastUsedAt: daysAgoIso(71),
      startedAt: daysAgoIso(380),
      nextChargeAt: daysFromNowIso(9),
      status: "active",
      bankDescriptor: "HULU",
    },
    {
      id: "demo-pf",
      merchantId: "planet-fitness",
      name: "Planet Fitness",
      amount: 24.99,
      cycle: "monthly",
      lastUsedAt: daysAgoIso(112),
      startedAt: daysAgoIso(640),
      nextChargeAt: daysFromNowIso(2),
      status: "active",
      bankDescriptor: "PLANET FITNESS",
      notes: "Home club requires a visit or a letter. Vale will not pretend otherwise.",
    },
    {
      id: "demo-calm",
      merchantId: "calm",
      name: "Calm",
      amount: 69.99,
      cycle: "yearly",
      lastUsedAt: daysAgoIso(180),
      startedAt: daysAgoIso(200),
      nextChargeAt: daysFromNowIso(185),
      status: "active",
      bankDescriptor: "CALM.COM",
    },
    {
      id: "demo-gpt",
      merchantId: "chatgpt",
      name: "ChatGPT Plus",
      amount: 20,
      cycle: "monthly",
      lastUsedAt: daysAgoIso(1),
      startedAt: daysAgoIso(90),
      nextChargeAt: daysFromNowIso(16),
      status: "active",
      bankDescriptor: "OPENAI *CHATGPT",
    },
    {
      id: "demo-adobe",
      merchantId: "adobe",
      name: "Adobe",
      amount: 54.99,
      cycle: "monthly",
      lastUsedAt: daysAgoIso(88),
      startedAt: daysAgoIso(300),
      nextChargeAt: daysFromNowIso(7),
      status: "active",
      bankDescriptor: "ADOBE *PHOTOSHOP",
    },
    {
      id: "demo-icloud",
      merchantId: "icloud",
      name: "iCloud+",
      amount: 2.99,
      cycle: "monthly",
      lastUsedAt: daysAgoIso(0),
      startedAt: daysAgoIso(800),
      nextChargeAt: daysFromNowIso(19),
      status: "active",
      bankDescriptor: "APPLE.COM/BILL",
    },
    {
      id: "demo-audible",
      merchantId: "audible",
      name: "Audible",
      amount: 14.95,
      cycle: "monthly",
      lastUsedAt: daysAgoIso(45),
      startedAt: daysAgoIso(220),
      nextChargeAt: daysFromNowIso(21),
      status: "active",
      bankDescriptor: "AUDIBLE",
    },
    {
      id: "demo-li",
      merchantId: "linkedin",
      name: "LinkedIn Premium",
      amount: 29.99,
      cycle: "monthly",
      lastUsedAt: daysAgoIso(200),
      startedAt: daysAgoIso(410),
      nextChargeAt: daysFromNowIso(5),
      status: "active",
      bankDescriptor: "LINKEDIN PREM",
    },
    {
      id: "demo-cp",
      merchantId: "classpass",
      name: "ClassPass",
      amount: 49,
      cycle: "monthly",
      lastUsedAt: daysAgoIso(63),
      startedAt: daysAgoIso(150),
      nextChargeAt: daysFromNowIso(13),
      status: "active",
      bankDescriptor: "CLASSPASS",
    },
    {
      id: "demo-nyt",
      merchantId: "nyt",
      name: "The New York Times",
      amount: 17,
      cycle: "monthly",
      lastUsedAt: daysAgoIso(5),
      startedAt: daysAgoIso(60),
      nextChargeAt: daysFromNowIso(25),
      status: "active",
      bankDescriptor: "NYTIMES DIGITAL",
    },
  ];
}

export function demoSavings(): SavingsEvent[] {
  return [
    {
      id: "demo-save-max",
      subscriptionId: "demo-max",
      name: "Max",
      monthlyAmount: 16.99,
      cancelledAt: daysAgoIso(18),
    },
  ];
}
